config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "profiles#new"
  resources :profiles
  # resources :profiles, only: [:new, :create, :show]
   # get '/register', to: 'users#new'
   # resources :users, except: [:new]

   # get 'login', to: 'sessions#new'
   # get 'logout', to: 'sessions#destroy'
   # post 'login', to: 'sessions#create' 
   
  resources :articles do
     resources :comments do 
      resources :replies
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in) 
      if user.type == "Admin"
        can :manage, :all
      else
        can [:read, :create], Article
        can [:update, :destroy], Article, user_id: user.id
        can [:read, :create], Comment
        can [:update, :destroy], Comment, user_id: user.id
        can [:destroy], Comment do |obj| 
          obj.article.user_id == user.id
        end
        can [:read, :create], Reply
        can [:update, :destroy], Reply, user_id: user.id
        can [:destroy], Comment do |obj|
          obj.article.user_id == user.id 
        end
      end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < User

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	scope :desce, -> { order("created_at DESC") }

	validates :title, presence: true
 	validates :body, presence: true, length: { minimum: 10 }
	#validates :author, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  
  has_many :replies, dependent: :destroy
  validates :body, presence: true
end

app/models/normal.rb
class Normal < User

end

app/models/profile.rb
class Profile < ApplicationRecord
	has_one_attached :image,dependent: :destroy
	belongs_to :user
	validates :name, presence: true
	validates :dob, presence: true
	validates :address, presence: true
	validates :image, presence: true
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  accepts_nested_attributes_for :profile
  after_update :welcome_email
  def welcome_email
    if self.confirmed_at?
    PostMailer.welcome_email(self).deliver
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token
	before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def ensure_current_user
    if current_user.profile.nil?
      redirect_to root_path
  end
end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [ profile_attributes: [:name, :dob, :address, :image, :user_id]])
  end
end
 

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :ensure_current_user

  def index
    @articles = Article.all.includes(:comments)
    @articles = Article.desce
    @article = Article.new
      respond_to do |format|
        format.html
        format.json {
          render json: @articles
        }
      end
  end
  
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
      if @article.save
      respond_to do |format|
        format.html {
          redirect_to root_path
        }
        format.json {
        render json: @article
        }
       end
      else
        @articles = Article.all
        render :index
      end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      respond_to do |format|
      format.html {redirect_to root_path}
      format.json {
        render json: @article
      }
    end
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json {
        render json: { mesage:"succesfully deleted" }
      }
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end

end

      

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params.merge(user_id: current_user.id))
    respond_to do |format|
        format.html {
          redirect_to root_path
        }
        format.json {
        render json: @comment
        }
    end
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to root_path
    else
     render :edit
    end
  end

  def destroy
    @article =Article.find(params[:article_id])
    @comment =@article.comments.find(params[:id])
    @comment.destroy
     redirect_to root_path
  end
  
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def show
		@profile = current_user.profile
	end

	def new
		if current_user.profile
			redirect_to articles_path
		else
		@profile = Profile.new
  end
end

  def create
    @profile = Profile.new(profile_params.merge(user_id: current_user.id))
    @profile.save
    redirect_to articles_path
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
  	@profile = Profile.find(params[:id])
    if @profile.update(profile_params)
     redirect_to root_path
    else
      render :edit
    end
  end

  private
    def profile_params
      params.require(:profile).permit(:name, :dob, :address, :image)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

	def create
    @comment = Comment.find(params[:comment_id])
    @reply = @comment.replies.create(reply_params.merge(user_id: current_user.id))
    if @reply.save
        redirect_to root_path
    end
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @reply =@comment.replies.find(params[:id])
    @reply.destroy
     redirect_to root_path
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:comment_id])
    @reply =@comment.replies.find(params[:id])
  end

  def update
    @reply = Reply.find(params[:id])
    # @comment = @article.comments.create(:id)
    if @reply.update(reply_params)
      redirect_to root_path
    else
      render :edit
    end
  end

private 
  def reply_params
     params.require(:reply).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/articles/_form.html.erb
<div class="form-actions"><br>
<h1>Create Post Here</h1>
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <br>
  </div>
  <div class="form-actions">
   <%= form.submit class: "btn btn-primary" %> 
  </div><br>

<% end %>

app/views/articles/_user.html.erb
<% if user_signed_in? %>
  <div><%= image_tag(current_user.profile.image, style:'width:100px; border-radius: 50%; margin-left: 500px') %></div>
  <h5 style = "margin-left:470px">Welcome <%= current_user.profile.name %></h5> 
  <div style = "margin-left:410px">
    <%= link_to "Show Profile",profile_path(current_user.profile) %>&nbsp &nbsp
    <%= link_to "Update Profile", edit_user_registration_path %>&nbsp &nbsp
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>&nbsp &nbsp
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1> 
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<%= render "user" %>
<%= render "form", article: @article %><br>
<h1 class="posts">Posts</h1>
<ul>
  <% @articles.each do |article| %>
  
    <li>
      <div><span class="heading">Title - </span><%=  article.title %></div>
    </li>  
      <div> <span class="heading">Body - </span><%= article.body %></div>
      <div><span class="heading">Author - </span><%= article.user.profile.name %></div>
    
       <% if can? :update, article %>
        <%= link_to "Edit", edit_article_path(article)%> &nbsp
        <%= link_to "Delete",article,method: :delete,
        data:{confirm: "are you sure?"} %>
       <%end%>
      <br>

      <h4>Comments(<%= article.comments.count %>)</h4>
      <%= render partial: 'comments/form', locals:{article: article} %>
      <% article.comments.reverse.each do |comment| %>
        <%= render partial: 'comments/comment', locals:{article: article,comment: comment} %>
        <%= render partial: 'replies/form', locals:{article: article,comment: comment} if comment.id.present? %>
      <% end %>     
  <% end %>
</ul>

app/views/comments/_comment.html.erb
<% if comment.persisted? %>
  <p>
    <%= comment.body%>&nbsp &nbsp By- <%= comment.user.profile.name %><br>
    <%= link_to "Edit", edit_article_comment_path(article_id: article.id, id: comment.id) if can? :edit, comment %>&nbsp 
    <%= link_to "Delete",[comment.article, comment],method: :delete,
        data:{ confirm: "are you sure?" } if can? :destroy, comment %>
  </p>
  <p>
    <% comment.replies.reverse.each do |reply| %>
        <p><%= reply.body %></p>
        <%= link_to "Edit", edit_article_comment_reply_path(article_id: article.id, comment_id: comment.id, id:reply.id) if can? :edit, reply %> 
        <%= link_to "Delete",article_comment_reply_path(article,comment,reply),method: :delete,data:{confirm: "are you sure?"} if can? :destroy, reply %> 
  <% end %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [article, article.comments.new ] do |form| %>
  <p>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<!-- <h1>Edit Comment</h1> -->
<%#= render "form", comment: @comment %>
<h4>Edit comment:</h4> 
  <%= form_with model: @comment, url: article_comment_path(@comment.article, @comment) do |form| %>
  <p>
    <%= form.text_field :body, placeholder: "body" %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Myapp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <br>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      <%= yield  %>
      <%#= yield :special_script %> 
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with model: @profile do |f| %>
  <div> 
    <%= f.label :username %><br/> 
    <%= f.text_field :name %>
    <% @profile.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div> 
    <%= f.label :DOB %><br/> 
    <%= f.date_field :dob %>
    <% @profile.errors.full_messages_for(:dob).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= f.label :Address %><br/> 
    <%= f.text_area :address %> 
    <% @profile.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= f.label :image %></br>
    <%= f.file_field :image %>
    <% @profile.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

app/views/profiles/edit.html.erb
<h1>Update Profile</h1>
 <%= render "form" %>

app/views/profiles/new.html.erb
<h1>Create Profile</h1>
 <%= render "form" %>

app/views/profiles/show.html.erb
 <h5>Your Profile </h5> </br>
    <div ><%= image_tag(current_user.profile.image, style:'width:100px; border-radius: 50%;') %></br>
   <strong>Name : </strong><%= current_user.profile.name %></br>
   <strong>Date of birth : </strong><%= @profile.dob %></br>
   <strong>Address :</strong><%= @profile.address %></br>
<%= link_to "Back", articles_path %>&nbsp 
<%= link_to "Edit", edit_user_registration_path %>&nbsp 

app/views/replies/_form.html.erb
<%#= form_for [comment.article, comment, comment.build_reply ] do |form| %>
<%= form_for [comment.article, comment, comment.replies.build ] do |form| %>
  <p>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/replies/edit.html.erb
<h4>Edit Reply:</h4>  
  <%= form_with model: @reply, url: article_comment_reply_path(@reply.comment.article, @reply) do |form| %>
  <p>
    <%= form.text_field :body, placeholder: "body" %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <% end %>